apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cravat-templates
spec:
  templates:
    - name: cravat-solo-template
      inputs:
        parameters:
          - name: proband-vcf
          - name: ref-version # 'hg38' or 'hg19'
          - name: annotators
          - name: modules-dir
            default: "/opt/open-cravat/cravat/modules"
          - name: output-dir
      volumes:
        - name: proband-vcf
          hostPath:
            path: "{{inputs.parameters.proband-vcf}}"
            type: File
        - name: modules-dir
          hostPath:
            path: "{{inputs.parameters.modules-dir}}"
            type: Directory
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate

      script:
        name: cravat-solo
        image: bergun/gennext-cravat:0.2.0-alpha
        command: [sh]
        source: |
          oc run \
          "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}" \
          -a {{inputs.parameters.annotators}} \
          -l {{inputs.parameters.ref-version}} \
          --skip reporter \
          --temp-files \
          --cleanrun \
          -d "{{inputs.parameters.output-dir}}"
        volumeMounts:
          - name: proband-vcf
            mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}"
          - name: modules-dir
            mountPath: "{{inputs.parameters.modules-dir}}"
          - name: output-dir
            # mountPath: "/mnt/output/"
            mountPath: "{{inputs.parameters.output-dir}}"
    # - name: cravat-duo-template
    #   inputs:
    #     parameters:
    #       - name: proband-vcf
    #       - name: case-vcf
    #       - name: ref-version
    #       - name: annotators
    #       - name: modules-dir
    #         default: "/opt/open-cravat/cravat/modules"
    #       - name: output-dir
    #   volumes:
    #     - name: proband-vcf
    #       hostPath:
    #         path: "{{inputs.parameters.proband-vcf}}"
    #         type: File
    #     - name: case-vcf
    #       hostPath:
    #         path: "{{inputs.parameters.case-vcf}}"
    #         type: File
    #     - name: modules-dir
    #       hostPath:
    #         path: "{{inputs.parameters.modules-dir}}"
    #         type: Directory
    #     - name: output-dir
    #       hostPath:
    #         path: "{{inputs.parameters.output-dir}}"
    #         type: DirectoryOrCreate
    #   script:
    #     name: cravat-duo
    #     image: bergun/gennext-cravat:0.2.0-alpha
    #     command: [sh]
    #     source: |
    #       oc run \
    #       "/mnt/input/{{=sprig.osBase(inputs.parameters['case-vcf'])}}" \
    #       "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}" \
    #       -a {{inputs.parameters.annotators}} \
    #       -l {{inputs.parameters.ref-version}} \
    #       --skip reporter \
    #       --temp-files \
    #       --cleanrun \
    #       -d "{{inputs.parameters.output-dir}}"
    #     volumeMounts:
    #       - name: proband-vcf
    #         mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['proband-vcf'])}}"
    #       - name: case-vcf
    #         mountPath: "/mnt/input/{{=sprig.osBase(inputs.parameters['case-vcf'])}}"
    #       - name: modules-dir
    #         mountPath: "/opt/"
    #       - name: output-dir
    #         mountPath: "/mnt/output/"
    #       - name: oc-modules
    #         mountPath: "/opt/open-cravat/cravat/modules"
