# Receives a number and subtracts by 2
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: subtract-test
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: number-count
      - name: node-name
  templates:
    - name: main
      inputs:
        parameters:
          - name: number-count
      outputs:
        parameters:
          - name: result
            value: "{{=int(inputs.parameters['number-count']) - 2}}"
      script:
        image: alpine:latest
        command: [sh]
        args: ["echo {{inputs.parameters.number-count}} - 2 | bc"]
  nodeSelector:
    kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
