apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: filter-and-annot-workflow
spec:
  entrypoint: filter-and-annot
  templates:
    - name: filter-and-annot
      inputs:
        parameters:
          - name: user-id
          - name: run-id
          - name: sample-id
          - name: output-rel-dir
            value: "/runspace/gennext/data/output/"
          - name: modules-base-dir
            value: "/runspace/gennext/data/modules/"
          - name: annots-base-dir
            value: "/runspace/gennext/data/annots/"
      outputs:
        parameters:
          - name: filtered-vcf
            valueFrom:
              parameter: "{{tasks.bcftools-filter-vcf.outputs.parameters.output-vcf-f}}"
      dag:
        tasks:
          - name: bcftools-filter-vcf
            templateRef:
              name: bcftools-template
              template: bcftools-filter-vcf
            arguments:
              parameters:
                - name: input-vcf-f
                  value: "{{inputs.parameters.output-rel-dir}}/{{inputs.parameters.user-id}}/{{inputs.parameters.run-id}}/vcf/{{inputs.parameters.sample-id}}_dv.vcf.gz"
                - name: output-vcf-f
                  value: "{{inputs.parameters.output-rel-dir}}/{{inputs.parameters.user-id}}/{{inputs.parameters.run-id}}/vcf/{{inputs.parameters.sample-id}}_dv_filtered.vcf.gz"
          - name: cravat
            templateRef:
              name: cravat-templates
              template: cravat-solo-template
            arguments:
              parameters:
                - name: proband-vcf
                  value: "{{tasks.bcftools-filter-vcf.outputs.parameters.output-vcf-f}}"
                - name: ref-version
                  value: "hg38"
                - name: annotators
                  value: "intervar cadd omim turkish_variome clinvar clinvar_acmg gme clinpred alphamissense gnomad4"
                - name: modules-dir
                  value: "{{inputs.parameters.modules-base-dir}}"
                - name: output-dir # TODO: retrieve base cravat jobs directory
                  value: "{{inputs.parameters.annots-base-dir}}/{{inputs.parameters.user-id}}/S_{{inputs.parameters.run-id}}"
            depends: "bcftools-filter-vcf"
