apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: manta-calls
spec:
  templates:
    - name: manta-calls
      inputs:
        parameters:
          - name: input-bam
          - name: sample-id
          - name: base-dir
          - name: temp-dir
          - name: annotsv-ref-dir
            default: "/runspace/gennext/data/ref/hg38/other/AnnotSV/"
          - name: sv-regions-file
            default: "/runspace/gennext/data/ref/hg38/regions/A3416642_SV_merged_AllTracks.bed"
          - name: thread-count
            default: "20"
          - name: ref-version
            default: "hg38"
      dag:
        tasks:
          - name: elprep
            templateRef:
              name: elprep-template
              template: elprep
            arguments:
              parameters:
                - name: sample-name
                  value: "{{inputs.parameters.sample-id}}"
                - name: genome-ref
                  value: "/runspace/gennext/data/ref/hg38/genome/GCA_000001405.15_GRCh38_full_minus_alt_plus_hs38d1_plus_HLA_analysis_set/GCA_000001405.15_GRCh38_full_minus_alt_plus_hs38d1_plus_HLA_analysis_set.fa"
                - name: regions-file
                  value: "/runspace/gennext/data/ref/hg38/regions/A3416642_AllTracks_merged.bed"
                - name: dbsnp-elsites-f
                  value: "/runspace/gennext/data/ref/hg38/dbSNP/GRCh38.dbSNP155.vcf.gz.elsites"
                - name: input-bam
                  value: "{{inputs.parameters.input-bam}}"
                - name: output-bam
                  value: "{{inputs.parameters.base-dir}}bam/{{inputs.parameters.sample-id}}_recal.bam"
                - name: metrics-dir
                  value: "{{inputs.parameters.base-dir}}metrics/"
                - name: scratch-dir
                  value: "{{inputs.parameters.temp-dir}}"
                - name: thread-count
                  value: "{{inputs.parameters.thread-count}}"
          - name: samtools-index
            templateRef:
              name: samtools-template
              template: samtools-index
            arguments:
              parameters:
                - name: input-bam
                  value: "{{tasks.elprep.outputs.parameters.output-bam}}"
                - name: thread-count
                  value: "{{inputs.parameters.thread-count}}"
            depends: "elprep"
          - name: manta
            templateRef:
              name: manta-template
              template: manta
            arguments:
              parameters:
                - name: tumor-bam
                  value: "{{tasks.elprep.outputs.parameters.output-bam}}"
                - name: ref-genome-f
                  # value: "{{tasks.get-abs-ref-dirs.outputs.parameters.ref-genome-f}}"
                  value: "/runspace/gennext/data/ref/hg38/genome/GCA_000001405.15_GRCh38_full_minus_alt_plus_hs38d1_plus_HLA_analysis_set/GCA_000001405.15_GRCh38_full_minus_alt_plus_hs38d1_plus_HLA_analysis_set.fa"
                - name: regions-file
                  # value: "{{tasks.get-abs-ref-dirs.outputs.parameters.somtest-A3416642-regions-sv-merged}}"
                  # value: ""
                  # value: "{{tasks.get-abs-ref-dirs.outputs.parameters.canonical-chroms-regions}}"
                  value: "/runspace/gennext/data/ref/hg38/regions/hg38_canonical_chrom_contig_regions.bed"
                - name: output-dir
                  value: "{{inputs.parameters.base-dir}}results/sv/"
                - name: scratch-dir
                  value: "{{inputs.parameters.temp-dir}}manta/"
                - name: thread-count
                  value: "{{inputs.parameters.thread-count}}"
            depends: "elprep && samtools-index"
          - name: bcftools-filter-and-bed
            templateRef:
              name: bcftools-template
              template: bcftools-filter-and-bed
            arguments:
              parameters:
                - name: input-vcf-f
                  value: "{{tasks.manta.outputs.parameters.output-tumor-vcf-f}}"
                  # value: "{{inputs.parameters.base-dir}}results/sv//tumorSV.vcf.gz"
                - name: output-vcf-f
                  value: "{{inputs.parameters.base-dir}}results/sv/{{inputs.parameters.sample-id}}_SV.vcf.gz"
                - name: regions-file
                  value: "{{inputs.parameters.sv-regions-file}}"
                - name: do-filter
                  value: ""
            depends: "manta"
          - name: annotsv
            templateRef:
              name: annotsv-template
              template: annotsv
            arguments:
              parameters:
                - name: input-vcf-f
                  value: "{{tasks.bcftools-filter-and-bed.outputs.parameters.output-vcf-f}}"
                - name: annotsv-ref-dir
                  value: "{{inputs.parameters.annotsv-ref-dir}}"
                - name: ref-version
                  value: "{{inputs.parameters.ref-version}}"
                - name: sv-min-size
                  value: "20"
                - name: output-annotsv-tsv-f
                  value: "{{inputs.parameters.temp-dir}}annotsv/{{inputs.parameters.sample-id}}_SV_annot.tsv"
            depends: "bcftools-filter-and-bed"
          - name: filter-annotsv
            templateRef:
              name: filter-annotsv-template
              template: filter-annotsv
            arguments:
              parameters:
                - name: sample-id
                  value: "{{inputs.parameters.sample-id}}"
                - name: annotsv-tsv
                  value: "{{tasks.annotsv.outputs.parameters.output-annotsv-tsv-f}}"
                - name: sv-cnv-geneslist-f
                  value: "/runspace/gennext/data/ref/hg38/geneslists/A3416642_SV_CNV_Genes.txt"
                - name: sv-translocations-geneslist-f
                  value: "/runspace/gennext/data/ref/hg38/geneslists/A3416642_SV_Translocation_Genes.txt"
                - name: annotsv-filtered-out-tsv
                  value: "{{inputs.parameters.base-dir}}results/sv/{{inputs.parameters.sample-id}}_SV_annot_filtered.tsv"
                - name: annotsv-oncokb-out-tsv
                  value: "{{inputs.parameters.temp-dir}}oncokb/{{inputs.parameters.sample-id}}_SV_oncokb.tsv"
            depends: "annotsv"
          - name: oncokb-sv
            templateRef:
              name: oncokb-templates
              template: oncokb-sv
            arguments:
              parameters:
                - name: oncokb-sv-in-f
                  value: "{{tasks.filter-annotsv.outputs.parameters.annotsv-oncokb-out-tsv}}"
                - name: oncokb-sv-out-f
                  value: "{{inputs.parameters.base-dir}}results/sv/{{inputs.parameters.sample-id}}_SV_oncokb_annot.tsv"
            depends: "filter-annotsv"
          - name: duckdb-sv
            templateRef:
              name: duckdb-template
              template: duckdb-sv
            arguments:
              parameters:
                - name: oncokb-tsv-f
                  value: "{{tasks.oncokb-sv.outputs.parameters.oncokb-sv-out-f}}"
                - name: annotsv-tsv-f
                  value: "{{tasks.filter-annotsv.outputs.parameters.annotsv-filtered-out-tsv}}"
                - name: output-duckdb
                  value: "{{inputs.parameters.base-dir}}results/db/{{inputs.parameters.sample-id}}_results.duckdb"
            depends: "oncokb-sv"
