FROM bergun/oncokb-annotator:v0.1.2

COPY filtered_maf_annotator.py /app/oncokb/filtered_maf_annotator.py
COPY filtered_sv_annotator.py /app/oncokb/filtered_sv_annotator.py
COPY backfill_filtered_maf.py /app/oncokb/backfill_filtered_maf.py
