apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: complete-workflow-test
  namespace: argo
spec:
  serviceAccountName: gennext-workflows
  entrypoint: complete-workflow-test
  arguments:
    parameters:
      - name: node-name
      - name: user-id
      - name: job-id
      - name: process-type
  podGC:
    strategy: OnPodSuccess
  nodeSelector:
    kubernetes.io/hostname: "{{workflow.parameters.node-name}}"
  templates:
    - name: complete-workflow-test
      dag:
        tasks:
          - name: get-node-config
            templateRef:
              name: get-node-config
              template: get-node-config
            arguments:
              parameters:
                - name: node-name
                  value: "{{workflow.parameters.node-name}}"
                - name: user-id
                  value: "{{workflow.parameters.user-id}}"
                - name: job-id
                  value: "{{workflow.parameters.job-id}}"
          - name: ces-workflow
            templateRef:
              name: ces-workflow
              template: main
            arguments:
              parameters:
                - name: input-rel-dir
                  value: "{{tasks.get-node-config.outputs.parameters.input-rel-dir}}"
                - name: temp-rel-dir
                  value: "{{tasks.get-node-config.outputs.parameters.temp-rel-dir}}"
                - name: scratch-rel-dir
                  value: "{{tasks.get-node-config.outputs.parameters.scratch-rel-dir}}"
                - name: output-rel-dir
                  value: "{{tasks.get-node-config.outputs.parameters.output-rel-dir}}"
                - name: ref-base-dir
                  value: "{{tasks.get-node-config.outputs.parameters.ref-base-dir}}"
                - name: job-id
                  value: "{{workflow.parameters.job-id}}"
                - name: thread-count
                  value: "{{tasks.get-node-config.outputs.parameters.thread-count}}"
            dependencies: [get-node-config]
  #   volumeMounts:
  #   - name: my-volume
  #     mountPath: /mnt
  # volumes:
  # - name: my-volume
  #   emptyDir: {}
