apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: annovar-to-maf-template
  namespace: argo
spec:
  templates:
    - name: annovar-to-maf
      inputs:
        parameters:
          - name: sample-id
          - name: annovar-out-f
          - name: ref-version
            value: "hg38"
      outputs:
        parameters:
          - name: annovar-maf-f
            value: "{{=sprig.osDir(inputs.parameters['annovar-out-f'])}}/{{inputs.parameters.sample-id}}.maf"
      volumes:
        - name: annovar-out-f
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['annovar-out-f'])}}"
            type: Directory
      script:
        name: annovar-script
        image: bergun/r-maftools:v0.0.1
        workingDir: /mnt/input/
        command: [sh]
        source: |
          Rscript -e "library(maftools); \
          maf = annovarToMaf(annovar='/mnt/input/{{=sprig.osBase(inputs.parameters['annovar-out-f'])}}', sep='\t', refBuild='{{inputs.parameters.ref-version}}', MAFobj=TRUE, basename='{{inputs.parameters.sample-id}}')"
        volumeMounts:
          - name: annovar-out-f
            mountPath: "/mnt/input/"
