apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: annovar-to-maf-template
  namespace: argo
spec:
  templates:
    - name: annovar-to-maf
      inputs:
        parameters:
          - name: sample-id
          - name: annovar-out-f
          - name: ref-version
            value: "hg38"
      outputs:
        parameters:
          - name: annovar-maf-f
            value: "{{=sprig.osDir(inputs.parameters['annovar-out-f'])}}/{{inputs.parameters.sample-id}}.maf"
      volumes:
        - name: annovar-out-f
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['annovar-out-f'])}}"
            type: Directory
      script:
        name: annovar-script
        image: bergun/maftools-rs:v0.1.0
        workingDir: /mnt/input/
        command: [sh]
        source: |
          set -e
          maftools-rs annovar-to-maf \
            --input "/mnt/input/{{=sprig.osBase(inputs.parameters['annovar-out-f'])}}" \
            --output "/mnt/input/{{inputs.parameters.sample-id}}.maf"
        resources:
          requests:
            cpu: "1"
            memory: 256Mi
          limits:
            memory: 2Gi
        volumeMounts:
          - name: annovar-out-f
            mountPath: "/mnt/input/"
