apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bwa-mem2-template
  namespace: argo
spec:
  templates:
    - name: bwa-mem2
      script:
        name: bwa-mem2-script
        image: bergun/bwa-mem2_samtools:0.0.1
        command: [sh]
        source: | #            -R {{workflow.parameters.read_group_header}} \
          bwa-mem2 mem -M \
          -R "{{inputs.parameters.read-group-str}}" \
          -t {{inputs.parameters.thread-count}} \
          /mnt/ref/{{=sprig.osBase(inputs.parameters['genome-ref'])}} \
          /mnt/input/r1/{{=sprig.osBase(inputs.parameters['fq-r1'])}} \
          /mnt/input/r2/{{=sprig.osBase(inputs.parameters['fq-r2'])}} \
          | samtools sort -@{{inputs.parameters.thread-count}} \
          -T /mnt/scratch/ -o /mnt/output/{{=sprig.osBase(inputs.parameters.bam)}}
        volumeMounts:
          - name: scratch
            mountPath: /mnt/scratch/
          - name: fq-r1
            mountPath: "/mnt/input/r1/{{=sprig.osBase(inputs.parameters['fq-r1'])}}"
          - name: fq-r2
            mountPath: "/mnt/input/r2/{{=sprig.osBase(inputs.parameters['fq-r2'])}}"
          - name: output
            mountPath: /mnt/output/
          - name: genome-ref
            mountPath: /mnt/ref/
      inputs:
        parameters:
          - name: fq-r1
          - name: fq-r2
          # - name: read_group_header
          - name: bam
          - name: genome-ref
          - name: scratch-dir
          - name: thread-count
          - name: read-group-str
      outputs:
        parameters:
          - name: bam
            value: "{{inputs.parameters.bam}}"
      volumes:
        - name: scratch
          hostPath:
            path: "{{inputs.parameters.scratch-dir}}"
        - name: output
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters.bam)}}"
        - name: fq-r1
          hostPath:
            path: "{{inputs.parameters.fq-r1}}"
        - name: fq-r2
          hostPath:
            path: "{{inputs.parameters.fq-r2}}"
        - name: genome-ref
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['genome-ref'])}}"
