apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: multiqc-template-test
  namespace: argo
spec:
  templates:
    - name: multiqc
      inputs:
        parameters:
          - name: input-dir
          - name: output-dir
      outputs:
        parameters:
          - name: output-dir
            value: "{{inputs.parameters.output-dir}}"
      volumes:
        - name: input-dir
          hostPath:
            path: "{{inputs.parameters.input-dir}}"
            type: Directory
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate
      script:
        name: multiqc-script
        image: quay.io/biocontainers/multiqc:1.27--pyhdfd78af_0
        command: [sh]
        source: |
          mkdir /mnt/output/multiqc_data;
          multiqc \
          /mnt/input/ \
          -o /mnt/output/
        volumeMounts:
          - name: input-dir
            mountPath: "/mnt/input/"
          - name: output-dir
            mountPath: "/mnt/output/"
  nodeSelector:
    kubernetes.io/hostname: gorillab-01
