apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: xyalign-template
  namespace: argo
spec:
  templates:
    - name: xyalign-exome
      inputs:
        parameters:
          - name: sample-name
          - name: input-bam
          - name: ref-genome-f
          # - name: regions-bed-f
          - name: output-dir
      outputs:
        parameters:
          - name: output-dir
            value: "{{inputs.parameters.output-dir}}"
      volumes:
        - name: input-bam
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['input-bam'])}}"
            type: Directory
        - name: ref-genome-f
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['ref-genome-f'])}}"
            type: Directory
        # - name: regions-bed-f
        #   hostPath:
        #     path: "{{inputs.parameters.regions-bed-f}}"
        #     type: File
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate
      script:
        name: xyalign-exome-script
        image: quay.io/biocontainers/xyalign:1.1.5--py_1
        command: [sh]
        workingDir: /mnt/output
        source: |
          xyalign \
          --ref /ref/genome/{{=sprig.osBase(inputs.parameters['ref-genome-f'])}} \
          --bam /input/{{=sprig.osBase(inputs.parameters['input-bam'])}} \
          --output_dir /output \
          --sample_id {{inputs.parameters.sample-name}} \
          --cpus 4 \
          --window_size 3000 \
          --chromosomes chr19 chrX chrY \
          --x_chromosome chrX \
          --y_chromosome chrY
        volumeMounts:
          - name: input-bam
            mountPath: "/mnt/input/bam/"
          - name: output-dir
            mountPath: "/mnt/output/"
          - name: ref-genome-f
            mountPath: "/ref/genome/"
          # - name: regions-file
          #   mountPath: "/mnt/input/bed/{{=sprig.osBase(inputs.parameters['regions-file'])}}"
    - name: xyalign-genome
      inputs:
        parameters:
          - name: sample-name
          - name: input-bam
          - name: ref-genome-f
          - name: output-dir
      outputs:
        parameters:
          - name: output-dir
            value: "{{inputs.parameters.output-dir}}"
      volumes:
        - name: input-bam
          hostPath:
            path: "{{=sprig.osDir(inputs.parameters['input-bam'])}}"
            type: Directory
        - name: output-dir
          hostPath:
            path: "{{inputs.parameters.output-dir}}"
            type: DirectoryOrCreate
      script:
        name: xyalign-genome-script
        image: quay.io/biocontainers/xyalign:1.1.5--py_1
        command: [sh]
        workingDir: /mnt/output
        source: |
          xyalign \
          --ref /mnt/ref/genome/{{=sprig.osBase(inputs.parameters['ref-genome-f'])}} \
        g--bam /mnt/input/bam/{{=sprig.osBase(inputs.parameters['input-bam'])}} \
          --output_dir /mnt/output \
          --sample_id {{inputs.parameters.sample-name}} \
          --cpus 4 \
          --window_size 5000 \
          --chromosomes chr19 chrX chrY \
          --x_chromosome chrX \
          --y_chromosome chrY
        volumeMounts:
          - name: input-bam
            mountPath: "/mnt/input/bam/"
          - name: ref-genome-f
            mountPath: "/mnt/ref/genome/"
          - name: output-dir
            mountPath: "/mnt/output/"