FROM quay.io/biocontainers/bedtools:2.31.1--hf5e1c6e_1

WORKDIR /tools

RUN wget https://github.com/shenwei356/seqkit/releases/download/v2.8.2/seqkit_linux_amd64.tar.gz
RUN tar -zxvf seqkit_linux_amd64.tar.gz